{% set name = "opentelemetry-exporter-otlp-proto-common" %}
{% set version = "1.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp_proto_common-{{ version }}.tar.gz
  sha256: 61db274d8a68d636fb2ec2a0f281922949361cdd8236e25ff5539edf942b3226

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - opentelemetry-proto =={{ version }}
  # NOTE backoff only required for py<37 but pip checks fails without it
    - backoff >=1.10.0,<2.0.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter.otlp.proto.common
  commands:
    - pip check
  requires:
    - pip

about:
  summary: OpenTelemetry Protobuf encoding
  license: Apache-2.0
  license_file: LICENSE
  home: https://opentelemetry.io/

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
