{% set name = "opentelemetry-exporter-otlp-proto-common" %}
{% set version = "1.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp_proto_common-{{ version }}.tar.gz
  sha256: bdbe50e2e22a1c71acaa0c8ba6efaadd58882e5a5978737a44a4c4b10d304c92

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - opentelemetry-proto =={{ version }}
  # NOTE backoff only required for py<37 but pip checks fails without it
    - backoff >=1.10.0,<3.0.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter.otlp.proto.common
  commands:
    - pip check
  requires:
    - pip

about:
  summary: OpenTelemetry Protobuf encoding
  license: Apache-2.0
  license_file: LICENSE
  home: https://opentelemetry.io/

extra:
  recipe-maintainers:
    - conda-forge/opentelemetry-proto
    - rxm7706
    - mariusvniekerk
