{% set name = "opentelemetry-exporter-otlp-proto-common" %}
{% set version = "1.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp_proto_common-{{ version }}.tar.gz
  sha256: df60c681bd61812e50b3a39a7a1afeeb6d4066117583249fcc262269374e7a49

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - opentelemetry-proto ==1.18.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter.otlp.proto.common
  commands:
    - pip check
  requires:
    - pip

about:
  summary: OpenTelemetry Protobuf encoding
  license: Apache-2.0
  license_file: LICENSE
  home: https://opentelemetry.io/

extra:
  recipe-maintainers:
    - mariusvniekerk
