{% set name = "opentelemetry-exporter-otlp-proto-common" %}
{% set version = "1.34.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp_proto_common-{{ version }}.tar.gz
  sha256: 5916d9ceda8c733adbec5e9cecf654fbf359e9f619ff43214277076fba888557

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-proto =={{ version }}
  # NOTE backoff only required for py<37 but pip checks fails without it
    - backoff >=1.10.0,<3.0.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter.otlp.proto.common
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: OpenTelemetry Protobuf encoding
  license: Apache-2.0
  license_file: LICENSE
  home: https://opentelemetry.io/

extra:
  recipe-maintainers:
    - conda-forge/opentelemetry-proto
    - rxm7706
    - mariusvniekerk
